package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestPaper<M extends BaseTestPaper<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAllTime(java.lang.Integer allTime) {
		set("all_time", allTime);
	}
	
	public java.lang.Integer getAllTime() {
		return getInt("all_time");
	}

	public void setStarttime(java.util.Date starttime) {
		set("starttime", starttime);
	}
	
	public java.util.Date getStarttime() {
		return get("starttime");
	}

	public void setEndtime(java.util.Date endtime) {
		set("endtime", endtime);
	}
	
	public java.util.Date getEndtime() {
		return get("endtime");
	}

	public void setFullMarks(java.lang.Integer fullMarks) {
		set("full_marks", fullMarks);
	}
	
	public java.lang.Integer getFullMarks() {
		return getInt("full_marks");
	}

	public void setSubjectId(java.lang.Integer subjectId) {
		set("subject_id", subjectId);
	}
	
	public java.lang.Integer getSubjectId() {
		return getInt("subject_id");
	}

}
