package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setTestPaperid(java.lang.Integer testPaperid) {
		set("test_paperid", testPaperid);
	}
	
	public java.lang.Integer getTestPaperid() {
		return getInt("test_paperid");
	}

	public void setClassid(java.lang.Integer classid) {
		set("classid", classid);
	}
	
	public java.lang.Integer getClassid() {
		return getInt("classid");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}
	
	public java.lang.Integer getScore() {
		return getInt("score");
	}

}
