package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}
	
	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}
	
	public java.lang.String getAnswer() {
		return getStr("answer");
	}

	public void setSubjectId(java.lang.Integer subjectId) {
		set("subject_id", subjectId);
	}
	
	public java.lang.Integer getSubjectId() {
		return getInt("subject_id");
	}

}
