package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSubject<M extends BaseSubject<M>> extends Model<M> implements IBean {

	public void setSubjectName(java.lang.String subjectName) {
		set("subject_name", subjectName);
	}
	
	public java.lang.String getSubjectName() {
		return getStr("subject_name");
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

}
