package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClass<M extends BaseClass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
	}
	
	public java.lang.Integer getTeacherId() {
		return getInt("teacher_id");
	}

	public void setTestPaperId(java.lang.Integer testPaperId) {
		set("test_paper_id", testPaperId);
	}
	
	public java.lang.Integer getTestPaperId() {
		return getInt("test_paper_id");
	}

}
