package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTempPaper<M extends BaseTempPaper<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTestPaperid(java.lang.Integer testPaperid) {
		set("test_paperid", testPaperid);
	}
	
	public java.lang.Integer getTestPaperid() {
		return getInt("test_paperid");
	}

	public void setTopicid(java.lang.Integer topicid) {
		set("topicid", topicid);
	}
	
	public java.lang.Integer getTopicid() {
		return getInt("topicid");
	}

}
