package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setClassId(java.lang.Integer classId) {
		set("class_id", classId);
	}
	
	public java.lang.Integer getClassId() {
		return getInt("class_id");
	}

	public void setUserlv(java.lang.Integer userlv) {
		set("userlv", userlv);
	}
	
	public java.lang.Integer getUserlv() {
		return getInt("userlv");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

}
