package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExam<M extends BaseExam<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTestpaperId(java.lang.Integer testpaperId) {
		set("testpaper_id", testpaperId);
	}
	
	public java.lang.Integer getTestpaperId() {
		return getInt("testpaper_id");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}
	
	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public void setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
	}
	
	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

}
