package com.demo.common.model;

import com.demo.common.model.base.BaseAdminUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUser extends BaseAdminUser<AdminUser> {
	
}
