package com.demo.common.model;

import com.demo.common.model.base.BaseTempPaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TempPaper extends BaseTempPaper<TempPaper> {
	
}
