package com.demo.common.model;

import com.demo.common.model.base.BaseTestPaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestPaper extends BaseTestPaper<TestPaper> {
	
}
